// This file was auto-generated by ML.NET Model Builder. 

using System;
using Kinect_Science_FairML.Model;

namespace Kinect_Science_FairML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Col1 = 0F,
                Col2 = 1F,
                Col3 = 2F,
                Col4 = 3F,
                Col5 = 4F,
                Col6 = 5F,
                Col7 = 6F,
                Col8 = 7F,
                Col9 = 8F,
                Col10 = 9F,
                Col11 = 10F,
                Col12 = 11F,
                Col13 = 12F,
                Col14 = 13F,
                Col15 = 14F,
                Col16 = 15F,
                Col17 = 16F,
                Col18 = 17F,
                Col19 = 18F,
                Col20 = 19F,
                Col21 = 20F,
                Col22 = 21F,
                Col23 = 22F,
                Col24 = 23F,
                Col25 = 24F,
                Col26 = 25F,
                Col27 = 26F,
                Col28 = 27F,
                Col29 = 28F,
                Col30 = 29F,
                Col31 = 30F,
                Col32 = 31F,
                Col33 = 32F,
                Col34 = 33F,
                Col35 = 34F,
                Col36 = 35F,
                Col37 = 36F,
                Col38 = 37F,
                Col39 = 38F,
                Col40 = 39F,
                Col41 = 40F,
                Col42 = 41F,
                Col43 = 42F,
                Col44 = 43F,
                Col45 = 44F,
                Col46 = 45F,
                Col47 = 46F,
                Col48 = 47F,
                Col49 = 48F,
                Col50 = 49F,
                Col51 = 50F,
                Col52 = 51F,
                Col53 = 52F,
                Col54 = 53F,
                Col55 = 54F,
                Col56 = 55F,
                Col57 = 56F,
                Col58 = 57F,
                Col59 = 58F,
                Col60 = 59F,
                Col61 = 60F,
                Col62 = 61F,
                Col63 = 62F,
                Col64 = 63F,
                Col65 = 64F,
                Col66 = 65F,
                Col67 = 66F,
                Col68 = 67F,
                Col69 = 68F,
                Col70 = 69F,
                Col71 = 70F,
                Col72 = 71F,
                Col73 = 72F,
                Col74 = 73F,
                Col75 = 74F,
                Col76 = 75F,
                Col77 = 76F,
                Col78 = 77F,
                Col79 = 78F,
                Col80 = 79F,
                Col81 = 80F,
                Col82 = 81F,
                Col83 = 82F,
                Col84 = 83F,
                Col85 = 84F,
                Col86 = 85F,
                Col87 = 86F,
                Col88 = 87F,
                Col89 = 88F,
                Col90 = 89F,
                Col91 = 90F,
                Col92 = 91F,
                Col93 = 92F,
                Col94 = 93F,
                Col95 = 94F,
                Col96 = 95F,
                Col97 = 96F,
                Col98 = 97F,
                Col99 = 98F,
                Col100 = 99F,
                Col101 = 100F,
                Col102 = 101F,
                Col103 = 102F,
                Col104 = 103F,
                Col105 = 104F,
                Col106 = 105F,
                Col107 = 106F,
                Col108 = 107F,
                Col109 = 108F,
                Col110 = 109F,
                Col111 = 110F,
                Col112 = 111F,
                Col113 = 112F,
                Col114 = 113F,
                Col115 = 114F,
                Col116 = 115F,
                Col117 = 116F,
                Col118 = 117F,
                Col119 = 118F,
                Col120 = 119F,
                Col121 = 120F,
                Col122 = 121F,
                Col123 = 122F,
                Col124 = 123F,
                Col125 = 124F,
                Col126 = 125F,
                Col127 = 126F,
                Col128 = 127F,
                Col129 = 128F,
                Col130 = 129F,
                Col131 = 130F,
                Col132 = 131F,
                Col133 = 132F,
                Col134 = 133F,
                Col135 = 134F,
                Col136 = 135F,
                Col137 = 136F,
                Col138 = 137F,
                Col139 = 138F,
                Col140 = 139F,
                Col141 = 140F,
                Col142 = 141F,
                Col143 = 142F,
                Col144 = 143F,
                Col145 = 144F,
                Col146 = 145F,
                Col147 = 146F,
                Col148 = 147F,
                Col149 = 148F,
                Col150 = 149F,
                Col151 = 150F,
                Col152 = 151F,
                Col153 = 152F,
                Col154 = 153F,
                Col155 = 154F,
                Col156 = 155F,
                Col157 = 156F,
                Col158 = 157F,
                Col159 = 158F,
                Col160 = 159F,
                Col161 = 160F,
                Col162 = 161F,
                Col163 = 162F,
                Col164 = 163F,
                Col165 = 164F,
                Col166 = 165F,
                Col167 = 166F,
                Col168 = 167F,
                Col169 = 168F,
                Col170 = 169F,
                Col171 = 170F,
                Col172 = 171F,
                Col173 = 172F,
                Col174 = 173F,
                Col175 = 174F,
                Col176 = 175F,
                Col177 = 176F,
                Col178 = 177F,
                Col179 = 178F,
                Col180 = 179F,
                Col181 = 180F,
                Col182 = 181F,
                Col183 = 182F,
                Col184 = 183F,
                Col185 = 184F,
                Col186 = 185F,
                Col187 = 186F,
                Col188 = 187F,
                Col189 = 188F,
                Col190 = 189F,
                Col191 = 190F,
                Col192 = 191F,
                Col193 = 192F,
                Col194 = 193F,
                Col195 = 194F,
                Col196 = 195F,
                Col197 = 196F,
                Col198 = 197F,
                Col199 = 198F,
                Col200 = 199F,
                Col201 = 200F,
                Col202 = 201F,
                Col203 = 202F,
                Col204 = 203F,
                Col205 = 204F,
                Col206 = 205F,
                Col207 = 206F,
                Col208 = 207F,
                Col209 = 208F,
                Col210 = 209F,
                Col211 = 210F,
                Col212 = 211F,
                Col213 = 212F,
                Col214 = 213F,
                Col215 = 214F,
                Col216 = 215F,
                Col217 = 216F,
                Col218 = 217F,
                Col219 = 218F,
                Col220 = 219F,
                Col221 = 220F,
                Col222 = 221F,
                Col223 = 222F,
                Col224 = 223F,
                Col225 = 224F,
                Col226 = 225F,
                Col227 = 226F,
                Col228 = 227F,
                Col229 = 228F,
                Col230 = 229F,
                Col231 = 230F,
                Col232 = 231F,
                Col233 = 232F,
                Col234 = 233F,
                Col235 = 234F,
                Col236 = 235F,
                Col237 = 236F,
                Col238 = 237F,
                Col239 = 238F,
                Col240 = 239F,
                Col241 = 240F,
                Col242 = 241F,
                Col243 = 242F,
                Col244 = 243F,
                Col245 = 244F,
                Col246 = 245F,
                Col247 = 246F,
                Col248 = 247F,
                Col249 = 248F,
                Col250 = 249F,
                Col251 = 250F,
                Col252 = 251F,
                Col253 = 252F,
                Col254 = 253F,
                Col255 = 254F,
                Col256 = 255F,
                Col257 = 256F,
                Col258 = 257F,
                Col259 = 258F,
                Col260 = 259F,
                Col261 = 260F,
                Col262 = 261F,
                Col263 = 262F,
                Col264 = 263F,
                Col265 = 264F,
                Col266 = 265F,
                Col267 = 266F,
                Col268 = 267F,
                Col269 = 268F,
                Col270 = 269F,
                Col271 = 270F,
                Col272 = 271F,
                Col273 = 272F,
                Col274 = 273F,
                Col275 = 274F,
                Col276 = 275F,
                Col277 = 276F,
                Col278 = 277F,
                Col279 = 278F,
                Col280 = 279F,
                Col281 = 280F,
                Col282 = 281F,
                Col283 = 282F,
                Col284 = 283F,
                Col285 = 284F,
                Col286 = 285F,
                Col287 = 286F,
                Col288 = 287F,
                Col289 = 288F,
                Col290 = 289F,
                Col291 = 290F,
                Col292 = 291F,
                Col293 = 292F,
                Col294 = 293F,
                Col295 = 294F,
                Col296 = 295F,
                Col297 = 296F,
                Col298 = 297F,
                Col299 = 298F,
                Col300 = 299F,
                Col301 = 300F,
                Col302 = 301F,
                Col303 = 302F,
                Col304 = 303F,
                Col305 = 304F,
                Col306 = 305F,
                Col307 = 306F,
                Col308 = 307F,
                Col309 = 308F,
                Col310 = 309F,
                Col311 = 310F,
                Col312 = 311F,
                Col313 = 312F,
                Col314 = 313F,
                Col315 = 314F,
                Col316 = 315F,
                Col317 = 316F,
                Col318 = 317F,
                Col319 = 318F,
                Col320 = 319F,
                Col321 = 320F,
                Col322 = 321F,
                Col323 = 322F,
                Col324 = 323F,
                Col325 = 324F,
                Col326 = 325F,
                Col327 = 326F,
                Col328 = 327F,
                Col329 = 328F,
                Col330 = 329F,
                Col331 = 330F,
                Col332 = 331F,
                Col333 = 332F,
                Col334 = 333F,
                Col335 = 334F,
                Col336 = 335F,
                Col337 = 336F,
                Col338 = 337F,
                Col339 = 338F,
                Col340 = 339F,
                Col341 = 340F,
                Col342 = 341F,
                Col343 = 342F,
                Col344 = 343F,
                Col345 = 344F,
                Col346 = 345F,
                Col347 = 346F,
                Col348 = 347F,
                Col349 = 348F,
                Col350 = 349F,
                Col351 = 350F,
                Col352 = 351F,
                Col353 = 352F,
                Col354 = 353F,
                Col355 = 354F,
                Col356 = 355F,
                Col357 = 356F,
                Col358 = 357F,
                Col359 = 358F,
                Col360 = 359F,
                Col361 = 360F,
                Col362 = 361F,
                Col363 = 362F,
                Col364 = 363F,
                Col365 = 364F,
                Col366 = 365F,
                Col367 = 366F,
                Col368 = 367F,
                Col369 = 368F,
                Col370 = 369F,
                Col371 = 370F,
                Col372 = 371F,
                Col373 = 372F,
                Col374 = 373F,
                Col375 = 374F,
                Col376 = 375F,
                Col377 = 376F,
                Col378 = 377F,
                Col379 = 378F,
                Col380 = 379F,
                Col381 = 380F,
                Col382 = 381F,
                Col383 = 382F,
                Col384 = 383F,
                Col385 = 384F,
                Col386 = 385F,
                Col387 = 386F,
                Col388 = 387F,
                Col389 = 388F,
                Col390 = 389F,
                Col391 = 390F,
                Col392 = 391F,
                Col393 = 392F,
                Col394 = 393F,
                Col395 = 394F,
                Col396 = 395F,
                Col397 = 396F,
                Col398 = 397F,
                Col399 = 398F,
                Col400 = 399F,
                Col401 = 400F,
                Col402 = 401F,
                Col403 = 402F,
                Col404 = 403F,
                Col405 = 404F,
                Col406 = 405F,
                Col407 = 406F,
                Col408 = 407F,
                Col409 = 408F,
                Col410 = 409F,
                Col411 = 410F,
                Col412 = 411F,
                Col413 = 412F,
                Col414 = 413F,
                Col415 = 414F,
                Col416 = 415F,
                Col417 = 416F,
                Col418 = 417F,
                Col419 = 418F,
                Col420 = 419F,
                Col421 = 420F,
                Col422 = 421F,
                Col423 = 422F,
                Col424 = 423F,
                Col425 = 424F,
                Col426 = 425F,
                Col427 = 426F,
                Col428 = 427F,
                Col429 = 428F,
                Col430 = 429F,
                Col431 = 430F,
                Col432 = 431F,
                Col433 = 432F,
                Col434 = 433F,
                Col435 = 434F,
                Col436 = 435F,
                Col437 = 436F,
                Col438 = 437F,
                Col439 = 438F,
                Col440 = 439F,
                Col441 = 440F,
                Col442 = 441F,
                Col443 = 442F,
                Col444 = 443F,
                Col445 = 444F,
                Col446 = 445F,
                Col447 = 446F,
                Col448 = 447F,
                Col449 = 448F,
                Col450 = 449F,
                Col451 = 450F,
                Col452 = 451F,
                Col453 = 452F,
                Col454 = 453F,
                Col455 = 454F,
                Col456 = 455F,
                Col457 = 456F,
                Col458 = 457F,
                Col459 = 458F,
                Col460 = 459F,
                Col461 = 460F,
                Col462 = 461F,
                Col463 = 462F,
                Col464 = 463F,
                Col465 = 464F,
                Col466 = 465F,
                Col467 = 466F,
                Col468 = 467F,
                Col469 = 468F,
                Col470 = 469F,
                Col471 = 470F,
                Col472 = 471F,
                Col473 = 472F,
                Col474 = 473F,
                Col475 = 474F,
                Col476 = 475F,
                Col477 = 476F,
                Col478 = 477F,
                Col479 = 478F,
                Col480 = 479F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");
            Console.WriteLine($"Col1: {sampleData.Col1}");
            Console.WriteLine($"Col2: {sampleData.Col2}");
            Console.WriteLine($"Col3: {sampleData.Col3}");
            Console.WriteLine($"Col4: {sampleData.Col4}");
            Console.WriteLine($"Col5: {sampleData.Col5}");
            Console.WriteLine($"Col6: {sampleData.Col6}");
            Console.WriteLine($"Col7: {sampleData.Col7}");
            Console.WriteLine($"Col8: {sampleData.Col8}");
            Console.WriteLine($"Col9: {sampleData.Col9}");
            Console.WriteLine($"Col10: {sampleData.Col10}");
            Console.WriteLine($"Col11: {sampleData.Col11}");
            Console.WriteLine($"Col12: {sampleData.Col12}");
            Console.WriteLine($"Col13: {sampleData.Col13}");
            Console.WriteLine($"Col14: {sampleData.Col14}");
            Console.WriteLine($"Col15: {sampleData.Col15}");
            Console.WriteLine($"Col16: {sampleData.Col16}");
            Console.WriteLine($"Col17: {sampleData.Col17}");
            Console.WriteLine($"Col18: {sampleData.Col18}");
            Console.WriteLine($"Col19: {sampleData.Col19}");
            Console.WriteLine($"Col20: {sampleData.Col20}");
            Console.WriteLine($"Col21: {sampleData.Col21}");
            Console.WriteLine($"Col22: {sampleData.Col22}");
            Console.WriteLine($"Col23: {sampleData.Col23}");
            Console.WriteLine($"Col24: {sampleData.Col24}");
            Console.WriteLine($"Col25: {sampleData.Col25}");
            Console.WriteLine($"Col26: {sampleData.Col26}");
            Console.WriteLine($"Col27: {sampleData.Col27}");
            Console.WriteLine($"Col28: {sampleData.Col28}");
            Console.WriteLine($"Col29: {sampleData.Col29}");
            Console.WriteLine($"Col30: {sampleData.Col30}");
            Console.WriteLine($"Col31: {sampleData.Col31}");
            Console.WriteLine($"Col32: {sampleData.Col32}");
            Console.WriteLine($"Col33: {sampleData.Col33}");
            Console.WriteLine($"Col34: {sampleData.Col34}");
            Console.WriteLine($"Col35: {sampleData.Col35}");
            Console.WriteLine($"Col36: {sampleData.Col36}");
            Console.WriteLine($"Col37: {sampleData.Col37}");
            Console.WriteLine($"Col38: {sampleData.Col38}");
            Console.WriteLine($"Col39: {sampleData.Col39}");
            Console.WriteLine($"Col40: {sampleData.Col40}");
            Console.WriteLine($"Col41: {sampleData.Col41}");
            Console.WriteLine($"Col42: {sampleData.Col42}");
            Console.WriteLine($"Col43: {sampleData.Col43}");
            Console.WriteLine($"Col44: {sampleData.Col44}");
            Console.WriteLine($"Col45: {sampleData.Col45}");
            Console.WriteLine($"Col46: {sampleData.Col46}");
            Console.WriteLine($"Col47: {sampleData.Col47}");
            Console.WriteLine($"Col48: {sampleData.Col48}");
            Console.WriteLine($"Col49: {sampleData.Col49}");
            Console.WriteLine($"Col50: {sampleData.Col50}");
            Console.WriteLine($"Col51: {sampleData.Col51}");
            Console.WriteLine($"Col52: {sampleData.Col52}");
            Console.WriteLine($"Col53: {sampleData.Col53}");
            Console.WriteLine($"Col54: {sampleData.Col54}");
            Console.WriteLine($"Col55: {sampleData.Col55}");
            Console.WriteLine($"Col56: {sampleData.Col56}");
            Console.WriteLine($"Col57: {sampleData.Col57}");
            Console.WriteLine($"Col58: {sampleData.Col58}");
            Console.WriteLine($"Col59: {sampleData.Col59}");
            Console.WriteLine($"Col60: {sampleData.Col60}");
            Console.WriteLine($"Col61: {sampleData.Col61}");
            Console.WriteLine($"Col62: {sampleData.Col62}");
            Console.WriteLine($"Col63: {sampleData.Col63}");
            Console.WriteLine($"Col64: {sampleData.Col64}");
            Console.WriteLine($"Col65: {sampleData.Col65}");
            Console.WriteLine($"Col66: {sampleData.Col66}");
            Console.WriteLine($"Col67: {sampleData.Col67}");
            Console.WriteLine($"Col68: {sampleData.Col68}");
            Console.WriteLine($"Col69: {sampleData.Col69}");
            Console.WriteLine($"Col70: {sampleData.Col70}");
            Console.WriteLine($"Col71: {sampleData.Col71}");
            Console.WriteLine($"Col72: {sampleData.Col72}");
            Console.WriteLine($"Col73: {sampleData.Col73}");
            Console.WriteLine($"Col74: {sampleData.Col74}");
            Console.WriteLine($"Col75: {sampleData.Col75}");
            Console.WriteLine($"Col76: {sampleData.Col76}");
            Console.WriteLine($"Col77: {sampleData.Col77}");
            Console.WriteLine($"Col78: {sampleData.Col78}");
            Console.WriteLine($"Col79: {sampleData.Col79}");
            Console.WriteLine($"Col80: {sampleData.Col80}");
            Console.WriteLine($"Col81: {sampleData.Col81}");
            Console.WriteLine($"Col82: {sampleData.Col82}");
            Console.WriteLine($"Col83: {sampleData.Col83}");
            Console.WriteLine($"Col84: {sampleData.Col84}");
            Console.WriteLine($"Col85: {sampleData.Col85}");
            Console.WriteLine($"Col86: {sampleData.Col86}");
            Console.WriteLine($"Col87: {sampleData.Col87}");
            Console.WriteLine($"Col88: {sampleData.Col88}");
            Console.WriteLine($"Col89: {sampleData.Col89}");
            Console.WriteLine($"Col90: {sampleData.Col90}");
            Console.WriteLine($"Col91: {sampleData.Col91}");
            Console.WriteLine($"Col92: {sampleData.Col92}");
            Console.WriteLine($"Col93: {sampleData.Col93}");
            Console.WriteLine($"Col94: {sampleData.Col94}");
            Console.WriteLine($"Col95: {sampleData.Col95}");
            Console.WriteLine($"Col96: {sampleData.Col96}");
            Console.WriteLine($"Col97: {sampleData.Col97}");
            Console.WriteLine($"Col98: {sampleData.Col98}");
            Console.WriteLine($"Col99: {sampleData.Col99}");
            Console.WriteLine($"Col100: {sampleData.Col100}");
            Console.WriteLine($"Col101: {sampleData.Col101}");
            Console.WriteLine($"Col102: {sampleData.Col102}");
            Console.WriteLine($"Col103: {sampleData.Col103}");
            Console.WriteLine($"Col104: {sampleData.Col104}");
            Console.WriteLine($"Col105: {sampleData.Col105}");
            Console.WriteLine($"Col106: {sampleData.Col106}");
            Console.WriteLine($"Col107: {sampleData.Col107}");
            Console.WriteLine($"Col108: {sampleData.Col108}");
            Console.WriteLine($"Col109: {sampleData.Col109}");
            Console.WriteLine($"Col110: {sampleData.Col110}");
            Console.WriteLine($"Col111: {sampleData.Col111}");
            Console.WriteLine($"Col112: {sampleData.Col112}");
            Console.WriteLine($"Col113: {sampleData.Col113}");
            Console.WriteLine($"Col114: {sampleData.Col114}");
            Console.WriteLine($"Col115: {sampleData.Col115}");
            Console.WriteLine($"Col116: {sampleData.Col116}");
            Console.WriteLine($"Col117: {sampleData.Col117}");
            Console.WriteLine($"Col118: {sampleData.Col118}");
            Console.WriteLine($"Col119: {sampleData.Col119}");
            Console.WriteLine($"Col120: {sampleData.Col120}");
            Console.WriteLine($"Col121: {sampleData.Col121}");
            Console.WriteLine($"Col122: {sampleData.Col122}");
            Console.WriteLine($"Col123: {sampleData.Col123}");
            Console.WriteLine($"Col124: {sampleData.Col124}");
            Console.WriteLine($"Col125: {sampleData.Col125}");
            Console.WriteLine($"Col126: {sampleData.Col126}");
            Console.WriteLine($"Col127: {sampleData.Col127}");
            Console.WriteLine($"Col128: {sampleData.Col128}");
            Console.WriteLine($"Col129: {sampleData.Col129}");
            Console.WriteLine($"Col130: {sampleData.Col130}");
            Console.WriteLine($"Col131: {sampleData.Col131}");
            Console.WriteLine($"Col132: {sampleData.Col132}");
            Console.WriteLine($"Col133: {sampleData.Col133}");
            Console.WriteLine($"Col134: {sampleData.Col134}");
            Console.WriteLine($"Col135: {sampleData.Col135}");
            Console.WriteLine($"Col136: {sampleData.Col136}");
            Console.WriteLine($"Col137: {sampleData.Col137}");
            Console.WriteLine($"Col138: {sampleData.Col138}");
            Console.WriteLine($"Col139: {sampleData.Col139}");
            Console.WriteLine($"Col140: {sampleData.Col140}");
            Console.WriteLine($"Col141: {sampleData.Col141}");
            Console.WriteLine($"Col142: {sampleData.Col142}");
            Console.WriteLine($"Col143: {sampleData.Col143}");
            Console.WriteLine($"Col144: {sampleData.Col144}");
            Console.WriteLine($"Col145: {sampleData.Col145}");
            Console.WriteLine($"Col146: {sampleData.Col146}");
            Console.WriteLine($"Col147: {sampleData.Col147}");
            Console.WriteLine($"Col148: {sampleData.Col148}");
            Console.WriteLine($"Col149: {sampleData.Col149}");
            Console.WriteLine($"Col150: {sampleData.Col150}");
            Console.WriteLine($"Col151: {sampleData.Col151}");
            Console.WriteLine($"Col152: {sampleData.Col152}");
            Console.WriteLine($"Col153: {sampleData.Col153}");
            Console.WriteLine($"Col154: {sampleData.Col154}");
            Console.WriteLine($"Col155: {sampleData.Col155}");
            Console.WriteLine($"Col156: {sampleData.Col156}");
            Console.WriteLine($"Col157: {sampleData.Col157}");
            Console.WriteLine($"Col158: {sampleData.Col158}");
            Console.WriteLine($"Col159: {sampleData.Col159}");
            Console.WriteLine($"Col160: {sampleData.Col160}");
            Console.WriteLine($"Col161: {sampleData.Col161}");
            Console.WriteLine($"Col162: {sampleData.Col162}");
            Console.WriteLine($"Col163: {sampleData.Col163}");
            Console.WriteLine($"Col164: {sampleData.Col164}");
            Console.WriteLine($"Col165: {sampleData.Col165}");
            Console.WriteLine($"Col166: {sampleData.Col166}");
            Console.WriteLine($"Col167: {sampleData.Col167}");
            Console.WriteLine($"Col168: {sampleData.Col168}");
            Console.WriteLine($"Col169: {sampleData.Col169}");
            Console.WriteLine($"Col170: {sampleData.Col170}");
            Console.WriteLine($"Col171: {sampleData.Col171}");
            Console.WriteLine($"Col172: {sampleData.Col172}");
            Console.WriteLine($"Col173: {sampleData.Col173}");
            Console.WriteLine($"Col174: {sampleData.Col174}");
            Console.WriteLine($"Col175: {sampleData.Col175}");
            Console.WriteLine($"Col176: {sampleData.Col176}");
            Console.WriteLine($"Col177: {sampleData.Col177}");
            Console.WriteLine($"Col178: {sampleData.Col178}");
            Console.WriteLine($"Col179: {sampleData.Col179}");
            Console.WriteLine($"Col180: {sampleData.Col180}");
            Console.WriteLine($"Col181: {sampleData.Col181}");
            Console.WriteLine($"Col182: {sampleData.Col182}");
            Console.WriteLine($"Col183: {sampleData.Col183}");
            Console.WriteLine($"Col184: {sampleData.Col184}");
            Console.WriteLine($"Col185: {sampleData.Col185}");
            Console.WriteLine($"Col186: {sampleData.Col186}");
            Console.WriteLine($"Col187: {sampleData.Col187}");
            Console.WriteLine($"Col188: {sampleData.Col188}");
            Console.WriteLine($"Col189: {sampleData.Col189}");
            Console.WriteLine($"Col190: {sampleData.Col190}");
            Console.WriteLine($"Col191: {sampleData.Col191}");
            Console.WriteLine($"Col192: {sampleData.Col192}");
            Console.WriteLine($"Col193: {sampleData.Col193}");
            Console.WriteLine($"Col194: {sampleData.Col194}");
            Console.WriteLine($"Col195: {sampleData.Col195}");
            Console.WriteLine($"Col196: {sampleData.Col196}");
            Console.WriteLine($"Col197: {sampleData.Col197}");
            Console.WriteLine($"Col198: {sampleData.Col198}");
            Console.WriteLine($"Col199: {sampleData.Col199}");
            Console.WriteLine($"Col200: {sampleData.Col200}");
            Console.WriteLine($"Col201: {sampleData.Col201}");
            Console.WriteLine($"Col202: {sampleData.Col202}");
            Console.WriteLine($"Col203: {sampleData.Col203}");
            Console.WriteLine($"Col204: {sampleData.Col204}");
            Console.WriteLine($"Col205: {sampleData.Col205}");
            Console.WriteLine($"Col206: {sampleData.Col206}");
            Console.WriteLine($"Col207: {sampleData.Col207}");
            Console.WriteLine($"Col208: {sampleData.Col208}");
            Console.WriteLine($"Col209: {sampleData.Col209}");
            Console.WriteLine($"Col210: {sampleData.Col210}");
            Console.WriteLine($"Col211: {sampleData.Col211}");
            Console.WriteLine($"Col212: {sampleData.Col212}");
            Console.WriteLine($"Col213: {sampleData.Col213}");
            Console.WriteLine($"Col214: {sampleData.Col214}");
            Console.WriteLine($"Col215: {sampleData.Col215}");
            Console.WriteLine($"Col216: {sampleData.Col216}");
            Console.WriteLine($"Col217: {sampleData.Col217}");
            Console.WriteLine($"Col218: {sampleData.Col218}");
            Console.WriteLine($"Col219: {sampleData.Col219}");
            Console.WriteLine($"Col220: {sampleData.Col220}");
            Console.WriteLine($"Col221: {sampleData.Col221}");
            Console.WriteLine($"Col222: {sampleData.Col222}");
            Console.WriteLine($"Col223: {sampleData.Col223}");
            Console.WriteLine($"Col224: {sampleData.Col224}");
            Console.WriteLine($"Col225: {sampleData.Col225}");
            Console.WriteLine($"Col226: {sampleData.Col226}");
            Console.WriteLine($"Col227: {sampleData.Col227}");
            Console.WriteLine($"Col228: {sampleData.Col228}");
            Console.WriteLine($"Col229: {sampleData.Col229}");
            Console.WriteLine($"Col230: {sampleData.Col230}");
            Console.WriteLine($"Col231: {sampleData.Col231}");
            Console.WriteLine($"Col232: {sampleData.Col232}");
            Console.WriteLine($"Col233: {sampleData.Col233}");
            Console.WriteLine($"Col234: {sampleData.Col234}");
            Console.WriteLine($"Col235: {sampleData.Col235}");
            Console.WriteLine($"Col236: {sampleData.Col236}");
            Console.WriteLine($"Col237: {sampleData.Col237}");
            Console.WriteLine($"Col238: {sampleData.Col238}");
            Console.WriteLine($"Col239: {sampleData.Col239}");
            Console.WriteLine($"Col240: {sampleData.Col240}");
            Console.WriteLine($"Col241: {sampleData.Col241}");
            Console.WriteLine($"Col242: {sampleData.Col242}");
            Console.WriteLine($"Col243: {sampleData.Col243}");
            Console.WriteLine($"Col244: {sampleData.Col244}");
            Console.WriteLine($"Col245: {sampleData.Col245}");
            Console.WriteLine($"Col246: {sampleData.Col246}");
            Console.WriteLine($"Col247: {sampleData.Col247}");
            Console.WriteLine($"Col248: {sampleData.Col248}");
            Console.WriteLine($"Col249: {sampleData.Col249}");
            Console.WriteLine($"Col250: {sampleData.Col250}");
            Console.WriteLine($"Col251: {sampleData.Col251}");
            Console.WriteLine($"Col252: {sampleData.Col252}");
            Console.WriteLine($"Col253: {sampleData.Col253}");
            Console.WriteLine($"Col254: {sampleData.Col254}");
            Console.WriteLine($"Col255: {sampleData.Col255}");
            Console.WriteLine($"Col256: {sampleData.Col256}");
            Console.WriteLine($"Col257: {sampleData.Col257}");
            Console.WriteLine($"Col258: {sampleData.Col258}");
            Console.WriteLine($"Col259: {sampleData.Col259}");
            Console.WriteLine($"Col260: {sampleData.Col260}");
            Console.WriteLine($"Col261: {sampleData.Col261}");
            Console.WriteLine($"Col262: {sampleData.Col262}");
            Console.WriteLine($"Col263: {sampleData.Col263}");
            Console.WriteLine($"Col264: {sampleData.Col264}");
            Console.WriteLine($"Col265: {sampleData.Col265}");
            Console.WriteLine($"Col266: {sampleData.Col266}");
            Console.WriteLine($"Col267: {sampleData.Col267}");
            Console.WriteLine($"Col268: {sampleData.Col268}");
            Console.WriteLine($"Col269: {sampleData.Col269}");
            Console.WriteLine($"Col270: {sampleData.Col270}");
            Console.WriteLine($"Col271: {sampleData.Col271}");
            Console.WriteLine($"Col272: {sampleData.Col272}");
            Console.WriteLine($"Col273: {sampleData.Col273}");
            Console.WriteLine($"Col274: {sampleData.Col274}");
            Console.WriteLine($"Col275: {sampleData.Col275}");
            Console.WriteLine($"Col276: {sampleData.Col276}");
            Console.WriteLine($"Col277: {sampleData.Col277}");
            Console.WriteLine($"Col278: {sampleData.Col278}");
            Console.WriteLine($"Col279: {sampleData.Col279}");
            Console.WriteLine($"Col280: {sampleData.Col280}");
            Console.WriteLine($"Col281: {sampleData.Col281}");
            Console.WriteLine($"Col282: {sampleData.Col282}");
            Console.WriteLine($"Col283: {sampleData.Col283}");
            Console.WriteLine($"Col284: {sampleData.Col284}");
            Console.WriteLine($"Col285: {sampleData.Col285}");
            Console.WriteLine($"Col286: {sampleData.Col286}");
            Console.WriteLine($"Col287: {sampleData.Col287}");
            Console.WriteLine($"Col288: {sampleData.Col288}");
            Console.WriteLine($"Col289: {sampleData.Col289}");
            Console.WriteLine($"Col290: {sampleData.Col290}");
            Console.WriteLine($"Col291: {sampleData.Col291}");
            Console.WriteLine($"Col292: {sampleData.Col292}");
            Console.WriteLine($"Col293: {sampleData.Col293}");
            Console.WriteLine($"Col294: {sampleData.Col294}");
            Console.WriteLine($"Col295: {sampleData.Col295}");
            Console.WriteLine($"Col296: {sampleData.Col296}");
            Console.WriteLine($"Col297: {sampleData.Col297}");
            Console.WriteLine($"Col298: {sampleData.Col298}");
            Console.WriteLine($"Col299: {sampleData.Col299}");
            Console.WriteLine($"Col300: {sampleData.Col300}");
            Console.WriteLine($"Col301: {sampleData.Col301}");
            Console.WriteLine($"Col302: {sampleData.Col302}");
            Console.WriteLine($"Col303: {sampleData.Col303}");
            Console.WriteLine($"Col304: {sampleData.Col304}");
            Console.WriteLine($"Col305: {sampleData.Col305}");
            Console.WriteLine($"Col306: {sampleData.Col306}");
            Console.WriteLine($"Col307: {sampleData.Col307}");
            Console.WriteLine($"Col308: {sampleData.Col308}");
            Console.WriteLine($"Col309: {sampleData.Col309}");
            Console.WriteLine($"Col310: {sampleData.Col310}");
            Console.WriteLine($"Col311: {sampleData.Col311}");
            Console.WriteLine($"Col312: {sampleData.Col312}");
            Console.WriteLine($"Col313: {sampleData.Col313}");
            Console.WriteLine($"Col314: {sampleData.Col314}");
            Console.WriteLine($"Col315: {sampleData.Col315}");
            Console.WriteLine($"Col316: {sampleData.Col316}");
            Console.WriteLine($"Col317: {sampleData.Col317}");
            Console.WriteLine($"Col318: {sampleData.Col318}");
            Console.WriteLine($"Col319: {sampleData.Col319}");
            Console.WriteLine($"Col320: {sampleData.Col320}");
            Console.WriteLine($"Col321: {sampleData.Col321}");
            Console.WriteLine($"Col322: {sampleData.Col322}");
            Console.WriteLine($"Col323: {sampleData.Col323}");
            Console.WriteLine($"Col324: {sampleData.Col324}");
            Console.WriteLine($"Col325: {sampleData.Col325}");
            Console.WriteLine($"Col326: {sampleData.Col326}");
            Console.WriteLine($"Col327: {sampleData.Col327}");
            Console.WriteLine($"Col328: {sampleData.Col328}");
            Console.WriteLine($"Col329: {sampleData.Col329}");
            Console.WriteLine($"Col330: {sampleData.Col330}");
            Console.WriteLine($"Col331: {sampleData.Col331}");
            Console.WriteLine($"Col332: {sampleData.Col332}");
            Console.WriteLine($"Col333: {sampleData.Col333}");
            Console.WriteLine($"Col334: {sampleData.Col334}");
            Console.WriteLine($"Col335: {sampleData.Col335}");
            Console.WriteLine($"Col336: {sampleData.Col336}");
            Console.WriteLine($"Col337: {sampleData.Col337}");
            Console.WriteLine($"Col338: {sampleData.Col338}");
            Console.WriteLine($"Col339: {sampleData.Col339}");
            Console.WriteLine($"Col340: {sampleData.Col340}");
            Console.WriteLine($"Col341: {sampleData.Col341}");
            Console.WriteLine($"Col342: {sampleData.Col342}");
            Console.WriteLine($"Col343: {sampleData.Col343}");
            Console.WriteLine($"Col344: {sampleData.Col344}");
            Console.WriteLine($"Col345: {sampleData.Col345}");
            Console.WriteLine($"Col346: {sampleData.Col346}");
            Console.WriteLine($"Col347: {sampleData.Col347}");
            Console.WriteLine($"Col348: {sampleData.Col348}");
            Console.WriteLine($"Col349: {sampleData.Col349}");
            Console.WriteLine($"Col350: {sampleData.Col350}");
            Console.WriteLine($"Col351: {sampleData.Col351}");
            Console.WriteLine($"Col352: {sampleData.Col352}");
            Console.WriteLine($"Col353: {sampleData.Col353}");
            Console.WriteLine($"Col354: {sampleData.Col354}");
            Console.WriteLine($"Col355: {sampleData.Col355}");
            Console.WriteLine($"Col356: {sampleData.Col356}");
            Console.WriteLine($"Col357: {sampleData.Col357}");
            Console.WriteLine($"Col358: {sampleData.Col358}");
            Console.WriteLine($"Col359: {sampleData.Col359}");
            Console.WriteLine($"Col360: {sampleData.Col360}");
            Console.WriteLine($"Col361: {sampleData.Col361}");
            Console.WriteLine($"Col362: {sampleData.Col362}");
            Console.WriteLine($"Col363: {sampleData.Col363}");
            Console.WriteLine($"Col364: {sampleData.Col364}");
            Console.WriteLine($"Col365: {sampleData.Col365}");
            Console.WriteLine($"Col366: {sampleData.Col366}");
            Console.WriteLine($"Col367: {sampleData.Col367}");
            Console.WriteLine($"Col368: {sampleData.Col368}");
            Console.WriteLine($"Col369: {sampleData.Col369}");
            Console.WriteLine($"Col370: {sampleData.Col370}");
            Console.WriteLine($"Col371: {sampleData.Col371}");
            Console.WriteLine($"Col372: {sampleData.Col372}");
            Console.WriteLine($"Col373: {sampleData.Col373}");
            Console.WriteLine($"Col374: {sampleData.Col374}");
            Console.WriteLine($"Col375: {sampleData.Col375}");
            Console.WriteLine($"Col376: {sampleData.Col376}");
            Console.WriteLine($"Col377: {sampleData.Col377}");
            Console.WriteLine($"Col378: {sampleData.Col378}");
            Console.WriteLine($"Col379: {sampleData.Col379}");
            Console.WriteLine($"Col380: {sampleData.Col380}");
            Console.WriteLine($"Col381: {sampleData.Col381}");
            Console.WriteLine($"Col382: {sampleData.Col382}");
            Console.WriteLine($"Col383: {sampleData.Col383}");
            Console.WriteLine($"Col384: {sampleData.Col384}");
            Console.WriteLine($"Col385: {sampleData.Col385}");
            Console.WriteLine($"Col386: {sampleData.Col386}");
            Console.WriteLine($"Col387: {sampleData.Col387}");
            Console.WriteLine($"Col388: {sampleData.Col388}");
            Console.WriteLine($"Col389: {sampleData.Col389}");
            Console.WriteLine($"Col390: {sampleData.Col390}");
            Console.WriteLine($"Col391: {sampleData.Col391}");
            Console.WriteLine($"Col392: {sampleData.Col392}");
            Console.WriteLine($"Col393: {sampleData.Col393}");
            Console.WriteLine($"Col394: {sampleData.Col394}");
            Console.WriteLine($"Col395: {sampleData.Col395}");
            Console.WriteLine($"Col396: {sampleData.Col396}");
            Console.WriteLine($"Col397: {sampleData.Col397}");
            Console.WriteLine($"Col398: {sampleData.Col398}");
            Console.WriteLine($"Col399: {sampleData.Col399}");
            Console.WriteLine($"Col400: {sampleData.Col400}");
            Console.WriteLine($"Col401: {sampleData.Col401}");
            Console.WriteLine($"Col402: {sampleData.Col402}");
            Console.WriteLine($"Col403: {sampleData.Col403}");
            Console.WriteLine($"Col404: {sampleData.Col404}");
            Console.WriteLine($"Col405: {sampleData.Col405}");
            Console.WriteLine($"Col406: {sampleData.Col406}");
            Console.WriteLine($"Col407: {sampleData.Col407}");
            Console.WriteLine($"Col408: {sampleData.Col408}");
            Console.WriteLine($"Col409: {sampleData.Col409}");
            Console.WriteLine($"Col410: {sampleData.Col410}");
            Console.WriteLine($"Col411: {sampleData.Col411}");
            Console.WriteLine($"Col412: {sampleData.Col412}");
            Console.WriteLine($"Col413: {sampleData.Col413}");
            Console.WriteLine($"Col414: {sampleData.Col414}");
            Console.WriteLine($"Col415: {sampleData.Col415}");
            Console.WriteLine($"Col416: {sampleData.Col416}");
            Console.WriteLine($"Col417: {sampleData.Col417}");
            Console.WriteLine($"Col418: {sampleData.Col418}");
            Console.WriteLine($"Col419: {sampleData.Col419}");
            Console.WriteLine($"Col420: {sampleData.Col420}");
            Console.WriteLine($"Col421: {sampleData.Col421}");
            Console.WriteLine($"Col422: {sampleData.Col422}");
            Console.WriteLine($"Col423: {sampleData.Col423}");
            Console.WriteLine($"Col424: {sampleData.Col424}");
            Console.WriteLine($"Col425: {sampleData.Col425}");
            Console.WriteLine($"Col426: {sampleData.Col426}");
            Console.WriteLine($"Col427: {sampleData.Col427}");
            Console.WriteLine($"Col428: {sampleData.Col428}");
            Console.WriteLine($"Col429: {sampleData.Col429}");
            Console.WriteLine($"Col430: {sampleData.Col430}");
            Console.WriteLine($"Col431: {sampleData.Col431}");
            Console.WriteLine($"Col432: {sampleData.Col432}");
            Console.WriteLine($"Col433: {sampleData.Col433}");
            Console.WriteLine($"Col434: {sampleData.Col434}");
            Console.WriteLine($"Col435: {sampleData.Col435}");
            Console.WriteLine($"Col436: {sampleData.Col436}");
            Console.WriteLine($"Col437: {sampleData.Col437}");
            Console.WriteLine($"Col438: {sampleData.Col438}");
            Console.WriteLine($"Col439: {sampleData.Col439}");
            Console.WriteLine($"Col440: {sampleData.Col440}");
            Console.WriteLine($"Col441: {sampleData.Col441}");
            Console.WriteLine($"Col442: {sampleData.Col442}");
            Console.WriteLine($"Col443: {sampleData.Col443}");
            Console.WriteLine($"Col444: {sampleData.Col444}");
            Console.WriteLine($"Col445: {sampleData.Col445}");
            Console.WriteLine($"Col446: {sampleData.Col446}");
            Console.WriteLine($"Col447: {sampleData.Col447}");
            Console.WriteLine($"Col448: {sampleData.Col448}");
            Console.WriteLine($"Col449: {sampleData.Col449}");
            Console.WriteLine($"Col450: {sampleData.Col450}");
            Console.WriteLine($"Col451: {sampleData.Col451}");
            Console.WriteLine($"Col452: {sampleData.Col452}");
            Console.WriteLine($"Col453: {sampleData.Col453}");
            Console.WriteLine($"Col454: {sampleData.Col454}");
            Console.WriteLine($"Col455: {sampleData.Col455}");
            Console.WriteLine($"Col456: {sampleData.Col456}");
            Console.WriteLine($"Col457: {sampleData.Col457}");
            Console.WriteLine($"Col458: {sampleData.Col458}");
            Console.WriteLine($"Col459: {sampleData.Col459}");
            Console.WriteLine($"Col460: {sampleData.Col460}");
            Console.WriteLine($"Col461: {sampleData.Col461}");
            Console.WriteLine($"Col462: {sampleData.Col462}");
            Console.WriteLine($"Col463: {sampleData.Col463}");
            Console.WriteLine($"Col464: {sampleData.Col464}");
            Console.WriteLine($"Col465: {sampleData.Col465}");
            Console.WriteLine($"Col466: {sampleData.Col466}");
            Console.WriteLine($"Col467: {sampleData.Col467}");
            Console.WriteLine($"Col468: {sampleData.Col468}");
            Console.WriteLine($"Col469: {sampleData.Col469}");
            Console.WriteLine($"Col470: {sampleData.Col470}");
            Console.WriteLine($"Col471: {sampleData.Col471}");
            Console.WriteLine($"Col472: {sampleData.Col472}");
            Console.WriteLine($"Col473: {sampleData.Col473}");
            Console.WriteLine($"Col474: {sampleData.Col474}");
            Console.WriteLine($"Col475: {sampleData.Col475}");
            Console.WriteLine($"Col476: {sampleData.Col476}");
            Console.WriteLine($"Col477: {sampleData.Col477}");
            Console.WriteLine($"Col478: {sampleData.Col478}");
            Console.WriteLine($"Col479: {sampleData.Col479}");
            Console.WriteLine($"Col480: {sampleData.Col480}");
            Console.WriteLine($"\n\nPredicted Col0 value {predictionResult.Prediction} \nPredicted Col0 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
