// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Kinect_Science_FairML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public string Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public float Col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public float Col2 { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public float Col3 { get; set; }


        [ColumnName("col4"), LoadColumn(4)]
        public float Col4 { get; set; }


        [ColumnName("col5"), LoadColumn(5)]
        public float Col5 { get; set; }


        [ColumnName("col6"), LoadColumn(6)]
        public float Col6 { get; set; }


        [ColumnName("col7"), LoadColumn(7)]
        public float Col7 { get; set; }


        [ColumnName("col8"), LoadColumn(8)]
        public float Col8 { get; set; }


        [ColumnName("col9"), LoadColumn(9)]
        public float Col9 { get; set; }


        [ColumnName("col10"), LoadColumn(10)]
        public float Col10 { get; set; }


        [ColumnName("col11"), LoadColumn(11)]
        public float Col11 { get; set; }


        [ColumnName("col12"), LoadColumn(12)]
        public float Col12 { get; set; }


        [ColumnName("col13"), LoadColumn(13)]
        public float Col13 { get; set; }


        [ColumnName("col14"), LoadColumn(14)]
        public float Col14 { get; set; }


        [ColumnName("col15"), LoadColumn(15)]
        public float Col15 { get; set; }


        [ColumnName("col16"), LoadColumn(16)]
        public float Col16 { get; set; }


        [ColumnName("col17"), LoadColumn(17)]
        public float Col17 { get; set; }


        [ColumnName("col18"), LoadColumn(18)]
        public float Col18 { get; set; }


        [ColumnName("col19"), LoadColumn(19)]
        public float Col19 { get; set; }


        [ColumnName("col20"), LoadColumn(20)]
        public float Col20 { get; set; }


        [ColumnName("col21"), LoadColumn(21)]
        public float Col21 { get; set; }


        [ColumnName("col22"), LoadColumn(22)]
        public float Col22 { get; set; }


        [ColumnName("col23"), LoadColumn(23)]
        public float Col23 { get; set; }


        [ColumnName("col24"), LoadColumn(24)]
        public float Col24 { get; set; }


        [ColumnName("col25"), LoadColumn(25)]
        public float Col25 { get; set; }


        [ColumnName("col26"), LoadColumn(26)]
        public float Col26 { get; set; }


        [ColumnName("col27"), LoadColumn(27)]
        public float Col27 { get; set; }


        [ColumnName("col28"), LoadColumn(28)]
        public float Col28 { get; set; }


        [ColumnName("col29"), LoadColumn(29)]
        public float Col29 { get; set; }


        [ColumnName("col30"), LoadColumn(30)]
        public float Col30 { get; set; }


        [ColumnName("col31"), LoadColumn(31)]
        public float Col31 { get; set; }


        [ColumnName("col32"), LoadColumn(32)]
        public float Col32 { get; set; }


        [ColumnName("col33"), LoadColumn(33)]
        public float Col33 { get; set; }


        [ColumnName("col34"), LoadColumn(34)]
        public float Col34 { get; set; }


        [ColumnName("col35"), LoadColumn(35)]
        public float Col35 { get; set; }


        [ColumnName("col36"), LoadColumn(36)]
        public float Col36 { get; set; }


        [ColumnName("col37"), LoadColumn(37)]
        public float Col37 { get; set; }


        [ColumnName("col38"), LoadColumn(38)]
        public float Col38 { get; set; }


        [ColumnName("col39"), LoadColumn(39)]
        public float Col39 { get; set; }


        [ColumnName("col40"), LoadColumn(40)]
        public float Col40 { get; set; }


        [ColumnName("col41"), LoadColumn(41)]
        public float Col41 { get; set; }


        [ColumnName("col42"), LoadColumn(42)]
        public float Col42 { get; set; }


        [ColumnName("col43"), LoadColumn(43)]
        public float Col43 { get; set; }


        [ColumnName("col44"), LoadColumn(44)]
        public float Col44 { get; set; }


        [ColumnName("col45"), LoadColumn(45)]
        public float Col45 { get; set; }


        [ColumnName("col46"), LoadColumn(46)]
        public float Col46 { get; set; }


        [ColumnName("col47"), LoadColumn(47)]
        public float Col47 { get; set; }


        [ColumnName("col48"), LoadColumn(48)]
        public float Col48 { get; set; }


        [ColumnName("col49"), LoadColumn(49)]
        public float Col49 { get; set; }


        [ColumnName("col50"), LoadColumn(50)]
        public float Col50 { get; set; }


        [ColumnName("col51"), LoadColumn(51)]
        public float Col51 { get; set; }


        [ColumnName("col52"), LoadColumn(52)]
        public float Col52 { get; set; }


        [ColumnName("col53"), LoadColumn(53)]
        public float Col53 { get; set; }


        [ColumnName("col54"), LoadColumn(54)]
        public float Col54 { get; set; }


        [ColumnName("col55"), LoadColumn(55)]
        public float Col55 { get; set; }


        [ColumnName("col56"), LoadColumn(56)]
        public float Col56 { get; set; }


        [ColumnName("col57"), LoadColumn(57)]
        public float Col57 { get; set; }


        [ColumnName("col58"), LoadColumn(58)]
        public float Col58 { get; set; }


        [ColumnName("col59"), LoadColumn(59)]
        public float Col59 { get; set; }


        [ColumnName("col60"), LoadColumn(60)]
        public float Col60 { get; set; }


        [ColumnName("col61"), LoadColumn(61)]
        public float Col61 { get; set; }


        [ColumnName("col62"), LoadColumn(62)]
        public float Col62 { get; set; }


        [ColumnName("col63"), LoadColumn(63)]
        public float Col63 { get; set; }


        [ColumnName("col64"), LoadColumn(64)]
        public float Col64 { get; set; }


        [ColumnName("col65"), LoadColumn(65)]
        public float Col65 { get; set; }


        [ColumnName("col66"), LoadColumn(66)]
        public float Col66 { get; set; }


        [ColumnName("col67"), LoadColumn(67)]
        public float Col67 { get; set; }


        [ColumnName("col68"), LoadColumn(68)]
        public float Col68 { get; set; }


        [ColumnName("col69"), LoadColumn(69)]
        public float Col69 { get; set; }


        [ColumnName("col70"), LoadColumn(70)]
        public float Col70 { get; set; }


        [ColumnName("col71"), LoadColumn(71)]
        public float Col71 { get; set; }


        [ColumnName("col72"), LoadColumn(72)]
        public float Col72 { get; set; }


        [ColumnName("col73"), LoadColumn(73)]
        public float Col73 { get; set; }


        [ColumnName("col74"), LoadColumn(74)]
        public float Col74 { get; set; }


        [ColumnName("col75"), LoadColumn(75)]
        public float Col75 { get; set; }


        [ColumnName("col76"), LoadColumn(76)]
        public float Col76 { get; set; }


        [ColumnName("col77"), LoadColumn(77)]
        public float Col77 { get; set; }


        [ColumnName("col78"), LoadColumn(78)]
        public float Col78 { get; set; }


        [ColumnName("col79"), LoadColumn(79)]
        public float Col79 { get; set; }


        [ColumnName("col80"), LoadColumn(80)]
        public float Col80 { get; set; }


        [ColumnName("col81"), LoadColumn(81)]
        public float Col81 { get; set; }


        [ColumnName("col82"), LoadColumn(82)]
        public float Col82 { get; set; }


        [ColumnName("col83"), LoadColumn(83)]
        public float Col83 { get; set; }


        [ColumnName("col84"), LoadColumn(84)]
        public float Col84 { get; set; }


        [ColumnName("col85"), LoadColumn(85)]
        public float Col85 { get; set; }


        [ColumnName("col86"), LoadColumn(86)]
        public float Col86 { get; set; }


        [ColumnName("col87"), LoadColumn(87)]
        public float Col87 { get; set; }


        [ColumnName("col88"), LoadColumn(88)]
        public float Col88 { get; set; }


        [ColumnName("col89"), LoadColumn(89)]
        public float Col89 { get; set; }


        [ColumnName("col90"), LoadColumn(90)]
        public float Col90 { get; set; }


        [ColumnName("col91"), LoadColumn(91)]
        public float Col91 { get; set; }


        [ColumnName("col92"), LoadColumn(92)]
        public float Col92 { get; set; }


        [ColumnName("col93"), LoadColumn(93)]
        public float Col93 { get; set; }


        [ColumnName("col94"), LoadColumn(94)]
        public float Col94 { get; set; }


        [ColumnName("col95"), LoadColumn(95)]
        public float Col95 { get; set; }


        [ColumnName("col96"), LoadColumn(96)]
        public float Col96 { get; set; }


        [ColumnName("col97"), LoadColumn(97)]
        public float Col97 { get; set; }


        [ColumnName("col98"), LoadColumn(98)]
        public float Col98 { get; set; }


        [ColumnName("col99"), LoadColumn(99)]
        public float Col99 { get; set; }


        [ColumnName("col100"), LoadColumn(100)]
        public float Col100 { get; set; }


        [ColumnName("col101"), LoadColumn(101)]
        public float Col101 { get; set; }


        [ColumnName("col102"), LoadColumn(102)]
        public float Col102 { get; set; }


        [ColumnName("col103"), LoadColumn(103)]
        public float Col103 { get; set; }


        [ColumnName("col104"), LoadColumn(104)]
        public float Col104 { get; set; }


        [ColumnName("col105"), LoadColumn(105)]
        public float Col105 { get; set; }


        [ColumnName("col106"), LoadColumn(106)]
        public float Col106 { get; set; }


        [ColumnName("col107"), LoadColumn(107)]
        public float Col107 { get; set; }


        [ColumnName("col108"), LoadColumn(108)]
        public float Col108 { get; set; }


        [ColumnName("col109"), LoadColumn(109)]
        public float Col109 { get; set; }


        [ColumnName("col110"), LoadColumn(110)]
        public float Col110 { get; set; }


        [ColumnName("col111"), LoadColumn(111)]
        public float Col111 { get; set; }


        [ColumnName("col112"), LoadColumn(112)]
        public float Col112 { get; set; }


        [ColumnName("col113"), LoadColumn(113)]
        public float Col113 { get; set; }


        [ColumnName("col114"), LoadColumn(114)]
        public float Col114 { get; set; }


        [ColumnName("col115"), LoadColumn(115)]
        public float Col115 { get; set; }


        [ColumnName("col116"), LoadColumn(116)]
        public float Col116 { get; set; }


        [ColumnName("col117"), LoadColumn(117)]
        public float Col117 { get; set; }


        [ColumnName("col118"), LoadColumn(118)]
        public float Col118 { get; set; }


        [ColumnName("col119"), LoadColumn(119)]
        public float Col119 { get; set; }


        [ColumnName("col120"), LoadColumn(120)]
        public float Col120 { get; set; }


        [ColumnName("col121"), LoadColumn(121)]
        public float Col121 { get; set; }


        [ColumnName("col122"), LoadColumn(122)]
        public float Col122 { get; set; }


        [ColumnName("col123"), LoadColumn(123)]
        public float Col123 { get; set; }


        [ColumnName("col124"), LoadColumn(124)]
        public float Col124 { get; set; }


        [ColumnName("col125"), LoadColumn(125)]
        public float Col125 { get; set; }


        [ColumnName("col126"), LoadColumn(126)]
        public float Col126 { get; set; }


        [ColumnName("col127"), LoadColumn(127)]
        public float Col127 { get; set; }


        [ColumnName("col128"), LoadColumn(128)]
        public float Col128 { get; set; }


        [ColumnName("col129"), LoadColumn(129)]
        public float Col129 { get; set; }


        [ColumnName("col130"), LoadColumn(130)]
        public float Col130 { get; set; }


        [ColumnName("col131"), LoadColumn(131)]
        public float Col131 { get; set; }


        [ColumnName("col132"), LoadColumn(132)]
        public float Col132 { get; set; }


        [ColumnName("col133"), LoadColumn(133)]
        public float Col133 { get; set; }


        [ColumnName("col134"), LoadColumn(134)]
        public float Col134 { get; set; }


        [ColumnName("col135"), LoadColumn(135)]
        public float Col135 { get; set; }


        [ColumnName("col136"), LoadColumn(136)]
        public float Col136 { get; set; }


        [ColumnName("col137"), LoadColumn(137)]
        public float Col137 { get; set; }


        [ColumnName("col138"), LoadColumn(138)]
        public float Col138 { get; set; }


        [ColumnName("col139"), LoadColumn(139)]
        public float Col139 { get; set; }


        [ColumnName("col140"), LoadColumn(140)]
        public float Col140 { get; set; }


        [ColumnName("col141"), LoadColumn(141)]
        public float Col141 { get; set; }


        [ColumnName("col142"), LoadColumn(142)]
        public float Col142 { get; set; }


        [ColumnName("col143"), LoadColumn(143)]
        public float Col143 { get; set; }


        [ColumnName("col144"), LoadColumn(144)]
        public float Col144 { get; set; }


        [ColumnName("col145"), LoadColumn(145)]
        public float Col145 { get; set; }


        [ColumnName("col146"), LoadColumn(146)]
        public float Col146 { get; set; }


        [ColumnName("col147"), LoadColumn(147)]
        public float Col147 { get; set; }


        [ColumnName("col148"), LoadColumn(148)]
        public float Col148 { get; set; }


        [ColumnName("col149"), LoadColumn(149)]
        public float Col149 { get; set; }


        [ColumnName("col150"), LoadColumn(150)]
        public float Col150 { get; set; }


        [ColumnName("col151"), LoadColumn(151)]
        public float Col151 { get; set; }


        [ColumnName("col152"), LoadColumn(152)]
        public float Col152 { get; set; }


        [ColumnName("col153"), LoadColumn(153)]
        public float Col153 { get; set; }


        [ColumnName("col154"), LoadColumn(154)]
        public float Col154 { get; set; }


        [ColumnName("col155"), LoadColumn(155)]
        public float Col155 { get; set; }


        [ColumnName("col156"), LoadColumn(156)]
        public float Col156 { get; set; }


        [ColumnName("col157"), LoadColumn(157)]
        public float Col157 { get; set; }


        [ColumnName("col158"), LoadColumn(158)]
        public float Col158 { get; set; }


        [ColumnName("col159"), LoadColumn(159)]
        public float Col159 { get; set; }


        [ColumnName("col160"), LoadColumn(160)]
        public float Col160 { get; set; }


        [ColumnName("col161"), LoadColumn(161)]
        public float Col161 { get; set; }


        [ColumnName("col162"), LoadColumn(162)]
        public float Col162 { get; set; }


        [ColumnName("col163"), LoadColumn(163)]
        public float Col163 { get; set; }


        [ColumnName("col164"), LoadColumn(164)]
        public float Col164 { get; set; }


        [ColumnName("col165"), LoadColumn(165)]
        public float Col165 { get; set; }


        [ColumnName("col166"), LoadColumn(166)]
        public float Col166 { get; set; }


        [ColumnName("col167"), LoadColumn(167)]
        public float Col167 { get; set; }


        [ColumnName("col168"), LoadColumn(168)]
        public float Col168 { get; set; }


        [ColumnName("col169"), LoadColumn(169)]
        public float Col169 { get; set; }


        [ColumnName("col170"), LoadColumn(170)]
        public float Col170 { get; set; }


        [ColumnName("col171"), LoadColumn(171)]
        public float Col171 { get; set; }


        [ColumnName("col172"), LoadColumn(172)]
        public float Col172 { get; set; }


        [ColumnName("col173"), LoadColumn(173)]
        public float Col173 { get; set; }


        [ColumnName("col174"), LoadColumn(174)]
        public float Col174 { get; set; }


        [ColumnName("col175"), LoadColumn(175)]
        public float Col175 { get; set; }


        [ColumnName("col176"), LoadColumn(176)]
        public float Col176 { get; set; }


        [ColumnName("col177"), LoadColumn(177)]
        public float Col177 { get; set; }


        [ColumnName("col178"), LoadColumn(178)]
        public float Col178 { get; set; }


        [ColumnName("col179"), LoadColumn(179)]
        public float Col179 { get; set; }


        [ColumnName("col180"), LoadColumn(180)]
        public float Col180 { get; set; }


        [ColumnName("col181"), LoadColumn(181)]
        public float Col181 { get; set; }


        [ColumnName("col182"), LoadColumn(182)]
        public float Col182 { get; set; }


        [ColumnName("col183"), LoadColumn(183)]
        public float Col183 { get; set; }


        [ColumnName("col184"), LoadColumn(184)]
        public float Col184 { get; set; }


        [ColumnName("col185"), LoadColumn(185)]
        public float Col185 { get; set; }


        [ColumnName("col186"), LoadColumn(186)]
        public float Col186 { get; set; }


        [ColumnName("col187"), LoadColumn(187)]
        public float Col187 { get; set; }


        [ColumnName("col188"), LoadColumn(188)]
        public float Col188 { get; set; }


        [ColumnName("col189"), LoadColumn(189)]
        public float Col189 { get; set; }


        [ColumnName("col190"), LoadColumn(190)]
        public float Col190 { get; set; }


        [ColumnName("col191"), LoadColumn(191)]
        public float Col191 { get; set; }


        [ColumnName("col192"), LoadColumn(192)]
        public float Col192 { get; set; }


        [ColumnName("col193"), LoadColumn(193)]
        public float Col193 { get; set; }


        [ColumnName("col194"), LoadColumn(194)]
        public float Col194 { get; set; }


        [ColumnName("col195"), LoadColumn(195)]
        public float Col195 { get; set; }


        [ColumnName("col196"), LoadColumn(196)]
        public float Col196 { get; set; }


        [ColumnName("col197"), LoadColumn(197)]
        public float Col197 { get; set; }


        [ColumnName("col198"), LoadColumn(198)]
        public float Col198 { get; set; }


        [ColumnName("col199"), LoadColumn(199)]
        public float Col199 { get; set; }


        [ColumnName("col200"), LoadColumn(200)]
        public float Col200 { get; set; }


        [ColumnName("col201"), LoadColumn(201)]
        public float Col201 { get; set; }


        [ColumnName("col202"), LoadColumn(202)]
        public float Col202 { get; set; }


        [ColumnName("col203"), LoadColumn(203)]
        public float Col203 { get; set; }


        [ColumnName("col204"), LoadColumn(204)]
        public float Col204 { get; set; }


        [ColumnName("col205"), LoadColumn(205)]
        public float Col205 { get; set; }


        [ColumnName("col206"), LoadColumn(206)]
        public float Col206 { get; set; }


        [ColumnName("col207"), LoadColumn(207)]
        public float Col207 { get; set; }


        [ColumnName("col208"), LoadColumn(208)]
        public float Col208 { get; set; }


        [ColumnName("col209"), LoadColumn(209)]
        public float Col209 { get; set; }


        [ColumnName("col210"), LoadColumn(210)]
        public float Col210 { get; set; }


        [ColumnName("col211"), LoadColumn(211)]
        public float Col211 { get; set; }


        [ColumnName("col212"), LoadColumn(212)]
        public float Col212 { get; set; }


        [ColumnName("col213"), LoadColumn(213)]
        public float Col213 { get; set; }


        [ColumnName("col214"), LoadColumn(214)]
        public float Col214 { get; set; }


        [ColumnName("col215"), LoadColumn(215)]
        public float Col215 { get; set; }


        [ColumnName("col216"), LoadColumn(216)]
        public float Col216 { get; set; }


        [ColumnName("col217"), LoadColumn(217)]
        public float Col217 { get; set; }


        [ColumnName("col218"), LoadColumn(218)]
        public float Col218 { get; set; }


        [ColumnName("col219"), LoadColumn(219)]
        public float Col219 { get; set; }


        [ColumnName("col220"), LoadColumn(220)]
        public float Col220 { get; set; }


        [ColumnName("col221"), LoadColumn(221)]
        public float Col221 { get; set; }


        [ColumnName("col222"), LoadColumn(222)]
        public float Col222 { get; set; }


        [ColumnName("col223"), LoadColumn(223)]
        public float Col223 { get; set; }


        [ColumnName("col224"), LoadColumn(224)]
        public float Col224 { get; set; }


        [ColumnName("col225"), LoadColumn(225)]
        public float Col225 { get; set; }


        [ColumnName("col226"), LoadColumn(226)]
        public float Col226 { get; set; }


        [ColumnName("col227"), LoadColumn(227)]
        public float Col227 { get; set; }


        [ColumnName("col228"), LoadColumn(228)]
        public float Col228 { get; set; }


        [ColumnName("col229"), LoadColumn(229)]
        public float Col229 { get; set; }


        [ColumnName("col230"), LoadColumn(230)]
        public float Col230 { get; set; }


        [ColumnName("col231"), LoadColumn(231)]
        public float Col231 { get; set; }


        [ColumnName("col232"), LoadColumn(232)]
        public float Col232 { get; set; }


        [ColumnName("col233"), LoadColumn(233)]
        public float Col233 { get; set; }


        [ColumnName("col234"), LoadColumn(234)]
        public float Col234 { get; set; }


        [ColumnName("col235"), LoadColumn(235)]
        public float Col235 { get; set; }


        [ColumnName("col236"), LoadColumn(236)]
        public float Col236 { get; set; }


        [ColumnName("col237"), LoadColumn(237)]
        public float Col237 { get; set; }


        [ColumnName("col238"), LoadColumn(238)]
        public float Col238 { get; set; }


        [ColumnName("col239"), LoadColumn(239)]
        public float Col239 { get; set; }


        [ColumnName("col240"), LoadColumn(240)]
        public float Col240 { get; set; }


        [ColumnName("col241"), LoadColumn(241)]
        public float Col241 { get; set; }


        [ColumnName("col242"), LoadColumn(242)]
        public float Col242 { get; set; }


        [ColumnName("col243"), LoadColumn(243)]
        public float Col243 { get; set; }


        [ColumnName("col244"), LoadColumn(244)]
        public float Col244 { get; set; }


        [ColumnName("col245"), LoadColumn(245)]
        public float Col245 { get; set; }


        [ColumnName("col246"), LoadColumn(246)]
        public float Col246 { get; set; }


        [ColumnName("col247"), LoadColumn(247)]
        public float Col247 { get; set; }


        [ColumnName("col248"), LoadColumn(248)]
        public float Col248 { get; set; }


        [ColumnName("col249"), LoadColumn(249)]
        public float Col249 { get; set; }


        [ColumnName("col250"), LoadColumn(250)]
        public float Col250 { get; set; }


        [ColumnName("col251"), LoadColumn(251)]
        public float Col251 { get; set; }


        [ColumnName("col252"), LoadColumn(252)]
        public float Col252 { get; set; }


        [ColumnName("col253"), LoadColumn(253)]
        public float Col253 { get; set; }


        [ColumnName("col254"), LoadColumn(254)]
        public float Col254 { get; set; }


        [ColumnName("col255"), LoadColumn(255)]
        public float Col255 { get; set; }


        [ColumnName("col256"), LoadColumn(256)]
        public float Col256 { get; set; }


        [ColumnName("col257"), LoadColumn(257)]
        public float Col257 { get; set; }


        [ColumnName("col258"), LoadColumn(258)]
        public float Col258 { get; set; }


        [ColumnName("col259"), LoadColumn(259)]
        public float Col259 { get; set; }


        [ColumnName("col260"), LoadColumn(260)]
        public float Col260 { get; set; }


        [ColumnName("col261"), LoadColumn(261)]
        public float Col261 { get; set; }


        [ColumnName("col262"), LoadColumn(262)]
        public float Col262 { get; set; }


        [ColumnName("col263"), LoadColumn(263)]
        public float Col263 { get; set; }


        [ColumnName("col264"), LoadColumn(264)]
        public float Col264 { get; set; }


        [ColumnName("col265"), LoadColumn(265)]
        public float Col265 { get; set; }


        [ColumnName("col266"), LoadColumn(266)]
        public float Col266 { get; set; }


        [ColumnName("col267"), LoadColumn(267)]
        public float Col267 { get; set; }


        [ColumnName("col268"), LoadColumn(268)]
        public float Col268 { get; set; }


        [ColumnName("col269"), LoadColumn(269)]
        public float Col269 { get; set; }


        [ColumnName("col270"), LoadColumn(270)]
        public float Col270 { get; set; }


        [ColumnName("col271"), LoadColumn(271)]
        public float Col271 { get; set; }


        [ColumnName("col272"), LoadColumn(272)]
        public float Col272 { get; set; }


        [ColumnName("col273"), LoadColumn(273)]
        public float Col273 { get; set; }


        [ColumnName("col274"), LoadColumn(274)]
        public float Col274 { get; set; }


        [ColumnName("col275"), LoadColumn(275)]
        public float Col275 { get; set; }


        [ColumnName("col276"), LoadColumn(276)]
        public float Col276 { get; set; }


        [ColumnName("col277"), LoadColumn(277)]
        public float Col277 { get; set; }


        [ColumnName("col278"), LoadColumn(278)]
        public float Col278 { get; set; }


        [ColumnName("col279"), LoadColumn(279)]
        public float Col279 { get; set; }


        [ColumnName("col280"), LoadColumn(280)]
        public float Col280 { get; set; }


        [ColumnName("col281"), LoadColumn(281)]
        public float Col281 { get; set; }


        [ColumnName("col282"), LoadColumn(282)]
        public float Col282 { get; set; }


        [ColumnName("col283"), LoadColumn(283)]
        public float Col283 { get; set; }


        [ColumnName("col284"), LoadColumn(284)]
        public float Col284 { get; set; }


        [ColumnName("col285"), LoadColumn(285)]
        public float Col285 { get; set; }


        [ColumnName("col286"), LoadColumn(286)]
        public float Col286 { get; set; }


        [ColumnName("col287"), LoadColumn(287)]
        public float Col287 { get; set; }


        [ColumnName("col288"), LoadColumn(288)]
        public float Col288 { get; set; }


        [ColumnName("col289"), LoadColumn(289)]
        public float Col289 { get; set; }


        [ColumnName("col290"), LoadColumn(290)]
        public float Col290 { get; set; }


        [ColumnName("col291"), LoadColumn(291)]
        public float Col291 { get; set; }


        [ColumnName("col292"), LoadColumn(292)]
        public float Col292 { get; set; }


        [ColumnName("col293"), LoadColumn(293)]
        public float Col293 { get; set; }


        [ColumnName("col294"), LoadColumn(294)]
        public float Col294 { get; set; }


        [ColumnName("col295"), LoadColumn(295)]
        public float Col295 { get; set; }


        [ColumnName("col296"), LoadColumn(296)]
        public float Col296 { get; set; }


        [ColumnName("col297"), LoadColumn(297)]
        public float Col297 { get; set; }


        [ColumnName("col298"), LoadColumn(298)]
        public float Col298 { get; set; }


        [ColumnName("col299"), LoadColumn(299)]
        public float Col299 { get; set; }


        [ColumnName("col300"), LoadColumn(300)]
        public float Col300 { get; set; }


        [ColumnName("col301"), LoadColumn(301)]
        public float Col301 { get; set; }


        [ColumnName("col302"), LoadColumn(302)]
        public float Col302 { get; set; }


        [ColumnName("col303"), LoadColumn(303)]
        public float Col303 { get; set; }


        [ColumnName("col304"), LoadColumn(304)]
        public float Col304 { get; set; }


        [ColumnName("col305"), LoadColumn(305)]
        public float Col305 { get; set; }


        [ColumnName("col306"), LoadColumn(306)]
        public float Col306 { get; set; }


        [ColumnName("col307"), LoadColumn(307)]
        public float Col307 { get; set; }


        [ColumnName("col308"), LoadColumn(308)]
        public float Col308 { get; set; }


        [ColumnName("col309"), LoadColumn(309)]
        public float Col309 { get; set; }


        [ColumnName("col310"), LoadColumn(310)]
        public float Col310 { get; set; }


        [ColumnName("col311"), LoadColumn(311)]
        public float Col311 { get; set; }


        [ColumnName("col312"), LoadColumn(312)]
        public float Col312 { get; set; }


        [ColumnName("col313"), LoadColumn(313)]
        public float Col313 { get; set; }


        [ColumnName("col314"), LoadColumn(314)]
        public float Col314 { get; set; }


        [ColumnName("col315"), LoadColumn(315)]
        public float Col315 { get; set; }


        [ColumnName("col316"), LoadColumn(316)]
        public float Col316 { get; set; }


        [ColumnName("col317"), LoadColumn(317)]
        public float Col317 { get; set; }


        [ColumnName("col318"), LoadColumn(318)]
        public float Col318 { get; set; }


        [ColumnName("col319"), LoadColumn(319)]
        public float Col319 { get; set; }


        [ColumnName("col320"), LoadColumn(320)]
        public float Col320 { get; set; }


        [ColumnName("col321"), LoadColumn(321)]
        public float Col321 { get; set; }


        [ColumnName("col322"), LoadColumn(322)]
        public float Col322 { get; set; }


        [ColumnName("col323"), LoadColumn(323)]
        public float Col323 { get; set; }


        [ColumnName("col324"), LoadColumn(324)]
        public float Col324 { get; set; }


        [ColumnName("col325"), LoadColumn(325)]
        public float Col325 { get; set; }


        [ColumnName("col326"), LoadColumn(326)]
        public float Col326 { get; set; }


        [ColumnName("col327"), LoadColumn(327)]
        public float Col327 { get; set; }


        [ColumnName("col328"), LoadColumn(328)]
        public float Col328 { get; set; }


        [ColumnName("col329"), LoadColumn(329)]
        public float Col329 { get; set; }


        [ColumnName("col330"), LoadColumn(330)]
        public float Col330 { get; set; }


        [ColumnName("col331"), LoadColumn(331)]
        public float Col331 { get; set; }


        [ColumnName("col332"), LoadColumn(332)]
        public float Col332 { get; set; }


        [ColumnName("col333"), LoadColumn(333)]
        public float Col333 { get; set; }


        [ColumnName("col334"), LoadColumn(334)]
        public float Col334 { get; set; }


        [ColumnName("col335"), LoadColumn(335)]
        public float Col335 { get; set; }


        [ColumnName("col336"), LoadColumn(336)]
        public float Col336 { get; set; }


        [ColumnName("col337"), LoadColumn(337)]
        public float Col337 { get; set; }


        [ColumnName("col338"), LoadColumn(338)]
        public float Col338 { get; set; }


        [ColumnName("col339"), LoadColumn(339)]
        public float Col339 { get; set; }


        [ColumnName("col340"), LoadColumn(340)]
        public float Col340 { get; set; }


        [ColumnName("col341"), LoadColumn(341)]
        public float Col341 { get; set; }


        [ColumnName("col342"), LoadColumn(342)]
        public float Col342 { get; set; }


        [ColumnName("col343"), LoadColumn(343)]
        public float Col343 { get; set; }


        [ColumnName("col344"), LoadColumn(344)]
        public float Col344 { get; set; }


        [ColumnName("col345"), LoadColumn(345)]
        public float Col345 { get; set; }


        [ColumnName("col346"), LoadColumn(346)]
        public float Col346 { get; set; }


        [ColumnName("col347"), LoadColumn(347)]
        public float Col347 { get; set; }


        [ColumnName("col348"), LoadColumn(348)]
        public float Col348 { get; set; }


        [ColumnName("col349"), LoadColumn(349)]
        public float Col349 { get; set; }


        [ColumnName("col350"), LoadColumn(350)]
        public float Col350 { get; set; }


        [ColumnName("col351"), LoadColumn(351)]
        public float Col351 { get; set; }


        [ColumnName("col352"), LoadColumn(352)]
        public float Col352 { get; set; }


        [ColumnName("col353"), LoadColumn(353)]
        public float Col353 { get; set; }


        [ColumnName("col354"), LoadColumn(354)]
        public float Col354 { get; set; }


        [ColumnName("col355"), LoadColumn(355)]
        public float Col355 { get; set; }


        [ColumnName("col356"), LoadColumn(356)]
        public float Col356 { get; set; }


        [ColumnName("col357"), LoadColumn(357)]
        public float Col357 { get; set; }


        [ColumnName("col358"), LoadColumn(358)]
        public float Col358 { get; set; }


        [ColumnName("col359"), LoadColumn(359)]
        public float Col359 { get; set; }


        [ColumnName("col360"), LoadColumn(360)]
        public float Col360 { get; set; }


        [ColumnName("col361"), LoadColumn(361)]
        public float Col361 { get; set; }


        [ColumnName("col362"), LoadColumn(362)]
        public float Col362 { get; set; }


        [ColumnName("col363"), LoadColumn(363)]
        public float Col363 { get; set; }


        [ColumnName("col364"), LoadColumn(364)]
        public float Col364 { get; set; }


        [ColumnName("col365"), LoadColumn(365)]
        public float Col365 { get; set; }


        [ColumnName("col366"), LoadColumn(366)]
        public float Col366 { get; set; }


        [ColumnName("col367"), LoadColumn(367)]
        public float Col367 { get; set; }


        [ColumnName("col368"), LoadColumn(368)]
        public float Col368 { get; set; }


        [ColumnName("col369"), LoadColumn(369)]
        public float Col369 { get; set; }


        [ColumnName("col370"), LoadColumn(370)]
        public float Col370 { get; set; }


        [ColumnName("col371"), LoadColumn(371)]
        public float Col371 { get; set; }


        [ColumnName("col372"), LoadColumn(372)]
        public float Col372 { get; set; }


        [ColumnName("col373"), LoadColumn(373)]
        public float Col373 { get; set; }


        [ColumnName("col374"), LoadColumn(374)]
        public float Col374 { get; set; }


        [ColumnName("col375"), LoadColumn(375)]
        public float Col375 { get; set; }


        [ColumnName("col376"), LoadColumn(376)]
        public float Col376 { get; set; }


        [ColumnName("col377"), LoadColumn(377)]
        public float Col377 { get; set; }


        [ColumnName("col378"), LoadColumn(378)]
        public float Col378 { get; set; }


        [ColumnName("col379"), LoadColumn(379)]
        public float Col379 { get; set; }


        [ColumnName("col380"), LoadColumn(380)]
        public float Col380 { get; set; }


        [ColumnName("col381"), LoadColumn(381)]
        public float Col381 { get; set; }


        [ColumnName("col382"), LoadColumn(382)]
        public float Col382 { get; set; }


        [ColumnName("col383"), LoadColumn(383)]
        public float Col383 { get; set; }


        [ColumnName("col384"), LoadColumn(384)]
        public float Col384 { get; set; }


        [ColumnName("col385"), LoadColumn(385)]
        public float Col385 { get; set; }


        [ColumnName("col386"), LoadColumn(386)]
        public float Col386 { get; set; }


        [ColumnName("col387"), LoadColumn(387)]
        public float Col387 { get; set; }


        [ColumnName("col388"), LoadColumn(388)]
        public float Col388 { get; set; }


        [ColumnName("col389"), LoadColumn(389)]
        public float Col389 { get; set; }


        [ColumnName("col390"), LoadColumn(390)]
        public float Col390 { get; set; }


        [ColumnName("col391"), LoadColumn(391)]
        public float Col391 { get; set; }


        [ColumnName("col392"), LoadColumn(392)]
        public float Col392 { get; set; }


        [ColumnName("col393"), LoadColumn(393)]
        public float Col393 { get; set; }


        [ColumnName("col394"), LoadColumn(394)]
        public float Col394 { get; set; }


        [ColumnName("col395"), LoadColumn(395)]
        public float Col395 { get; set; }


        [ColumnName("col396"), LoadColumn(396)]
        public float Col396 { get; set; }


        [ColumnName("col397"), LoadColumn(397)]
        public float Col397 { get; set; }


        [ColumnName("col398"), LoadColumn(398)]
        public float Col398 { get; set; }


        [ColumnName("col399"), LoadColumn(399)]
        public float Col399 { get; set; }


        [ColumnName("col400"), LoadColumn(400)]
        public float Col400 { get; set; }


        [ColumnName("col401"), LoadColumn(401)]
        public float Col401 { get; set; }


        [ColumnName("col402"), LoadColumn(402)]
        public float Col402 { get; set; }


        [ColumnName("col403"), LoadColumn(403)]
        public float Col403 { get; set; }


        [ColumnName("col404"), LoadColumn(404)]
        public float Col404 { get; set; }


        [ColumnName("col405"), LoadColumn(405)]
        public float Col405 { get; set; }


        [ColumnName("col406"), LoadColumn(406)]
        public float Col406 { get; set; }


        [ColumnName("col407"), LoadColumn(407)]
        public float Col407 { get; set; }


        [ColumnName("col408"), LoadColumn(408)]
        public float Col408 { get; set; }


        [ColumnName("col409"), LoadColumn(409)]
        public float Col409 { get; set; }


        [ColumnName("col410"), LoadColumn(410)]
        public float Col410 { get; set; }


        [ColumnName("col411"), LoadColumn(411)]
        public float Col411 { get; set; }


        [ColumnName("col412"), LoadColumn(412)]
        public float Col412 { get; set; }


        [ColumnName("col413"), LoadColumn(413)]
        public float Col413 { get; set; }


        [ColumnName("col414"), LoadColumn(414)]
        public float Col414 { get; set; }


        [ColumnName("col415"), LoadColumn(415)]
        public float Col415 { get; set; }


        [ColumnName("col416"), LoadColumn(416)]
        public float Col416 { get; set; }


        [ColumnName("col417"), LoadColumn(417)]
        public float Col417 { get; set; }


        [ColumnName("col418"), LoadColumn(418)]
        public float Col418 { get; set; }


        [ColumnName("col419"), LoadColumn(419)]
        public float Col419 { get; set; }


        [ColumnName("col420"), LoadColumn(420)]
        public float Col420 { get; set; }


        [ColumnName("col421"), LoadColumn(421)]
        public float Col421 { get; set; }


        [ColumnName("col422"), LoadColumn(422)]
        public float Col422 { get; set; }


        [ColumnName("col423"), LoadColumn(423)]
        public float Col423 { get; set; }


        [ColumnName("col424"), LoadColumn(424)]
        public float Col424 { get; set; }


        [ColumnName("col425"), LoadColumn(425)]
        public float Col425 { get; set; }


        [ColumnName("col426"), LoadColumn(426)]
        public float Col426 { get; set; }


        [ColumnName("col427"), LoadColumn(427)]
        public float Col427 { get; set; }


        [ColumnName("col428"), LoadColumn(428)]
        public float Col428 { get; set; }


        [ColumnName("col429"), LoadColumn(429)]
        public float Col429 { get; set; }


        [ColumnName("col430"), LoadColumn(430)]
        public float Col430 { get; set; }


        [ColumnName("col431"), LoadColumn(431)]
        public float Col431 { get; set; }


        [ColumnName("col432"), LoadColumn(432)]
        public float Col432 { get; set; }


        [ColumnName("col433"), LoadColumn(433)]
        public float Col433 { get; set; }


        [ColumnName("col434"), LoadColumn(434)]
        public float Col434 { get; set; }


        [ColumnName("col435"), LoadColumn(435)]
        public float Col435 { get; set; }


        [ColumnName("col436"), LoadColumn(436)]
        public float Col436 { get; set; }


        [ColumnName("col437"), LoadColumn(437)]
        public float Col437 { get; set; }


        [ColumnName("col438"), LoadColumn(438)]
        public float Col438 { get; set; }


        [ColumnName("col439"), LoadColumn(439)]
        public float Col439 { get; set; }


        [ColumnName("col440"), LoadColumn(440)]
        public float Col440 { get; set; }


        [ColumnName("col441"), LoadColumn(441)]
        public float Col441 { get; set; }


        [ColumnName("col442"), LoadColumn(442)]
        public float Col442 { get; set; }


        [ColumnName("col443"), LoadColumn(443)]
        public float Col443 { get; set; }


        [ColumnName("col444"), LoadColumn(444)]
        public float Col444 { get; set; }


        [ColumnName("col445"), LoadColumn(445)]
        public float Col445 { get; set; }


        [ColumnName("col446"), LoadColumn(446)]
        public float Col446 { get; set; }


        [ColumnName("col447"), LoadColumn(447)]
        public float Col447 { get; set; }


        [ColumnName("col448"), LoadColumn(448)]
        public float Col448 { get; set; }


        [ColumnName("col449"), LoadColumn(449)]
        public float Col449 { get; set; }


        [ColumnName("col450"), LoadColumn(450)]
        public float Col450 { get; set; }


        [ColumnName("col451"), LoadColumn(451)]
        public float Col451 { get; set; }


        [ColumnName("col452"), LoadColumn(452)]
        public float Col452 { get; set; }


        [ColumnName("col453"), LoadColumn(453)]
        public float Col453 { get; set; }


        [ColumnName("col454"), LoadColumn(454)]
        public float Col454 { get; set; }


        [ColumnName("col455"), LoadColumn(455)]
        public float Col455 { get; set; }


        [ColumnName("col456"), LoadColumn(456)]
        public float Col456 { get; set; }


        [ColumnName("col457"), LoadColumn(457)]
        public float Col457 { get; set; }


        [ColumnName("col458"), LoadColumn(458)]
        public float Col458 { get; set; }


        [ColumnName("col459"), LoadColumn(459)]
        public float Col459 { get; set; }


        [ColumnName("col460"), LoadColumn(460)]
        public float Col460 { get; set; }


        [ColumnName("col461"), LoadColumn(461)]
        public float Col461 { get; set; }


        [ColumnName("col462"), LoadColumn(462)]
        public float Col462 { get; set; }


        [ColumnName("col463"), LoadColumn(463)]
        public float Col463 { get; set; }


        [ColumnName("col464"), LoadColumn(464)]
        public float Col464 { get; set; }


        [ColumnName("col465"), LoadColumn(465)]
        public float Col465 { get; set; }


        [ColumnName("col466"), LoadColumn(466)]
        public float Col466 { get; set; }


        [ColumnName("col467"), LoadColumn(467)]
        public float Col467 { get; set; }


        [ColumnName("col468"), LoadColumn(468)]
        public float Col468 { get; set; }


        [ColumnName("col469"), LoadColumn(469)]
        public float Col469 { get; set; }


        [ColumnName("col470"), LoadColumn(470)]
        public float Col470 { get; set; }


        [ColumnName("col471"), LoadColumn(471)]
        public float Col471 { get; set; }


        [ColumnName("col472"), LoadColumn(472)]
        public float Col472 { get; set; }


        [ColumnName("col473"), LoadColumn(473)]
        public float Col473 { get; set; }


        [ColumnName("col474"), LoadColumn(474)]
        public float Col474 { get; set; }


        [ColumnName("col475"), LoadColumn(475)]
        public float Col475 { get; set; }


        [ColumnName("col476"), LoadColumn(476)]
        public float Col476 { get; set; }


        [ColumnName("col477"), LoadColumn(477)]
        public float Col477 { get; set; }


        [ColumnName("col478"), LoadColumn(478)]
        public float Col478 { get; set; }


        [ColumnName("col479"), LoadColumn(479)]
        public float Col479 { get; set; }


        [ColumnName("col480"), LoadColumn(480)]
        public float Col480 { get; set; }


    }
}
